name: sudoku-web
version: 0.1.0
dependencies:
  - base >= 4.7 && < 5
  - scotty
  - aeson
  - text
  - containers
  - mtl
  - hspec
  - lens
executables:
  sudoku-web:
    main: Main.hs
    source-dirs: app
library:
  source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
